env:
  global:
    - secure: zVB0VMdfr5X0KiICi/6sR8y6xsbQhN/a95To3J790TDUgeZJfMMA5/y3L30SX87N3QZxNUw9ZN39+BmHMDgEJUsJSKsShQ8or249HRmB/jPblTJKGouGYlaF780Q1pl/3R0+A9sDzoM1wsrvCzvhVJ6RQP8pivLCH6leDUdFl7tNP7+N7d7gh8dgycmpkTd4YAU7V/8581wtXjs1IdGh9e83Xys3pwKhSp4S+QMTRMRBKIlH2eGdPQJvR4Upvodl0e/ViCSCBBfmOsgKO4/DIo248LqgSDKIAD9vzl9+byugh6v5C/SGWyasp80CZu0hcc+01NPQs8/I5U3j0NTV0KRMV8gjWMZd4RvdsTkpOuxo+HAB0mRnrEnViqEZMpB+nI0fXmwD+UhHhFP/sI2aYYSzAGVXABHdrEZfbMHWekPC62GAzsnIXqCnjGit93zf3gHqQoPaQSNMzhnEFLpIzeSW8ZtWmNPYjPawSXDwo9NilNGN0PWsDi+Ut9ZfCO7Xi+VyQMrjz4BG0dtSvne5aERmWZR0hXJsoEazm+5QBKZEqwF21AcItvtZJum+uHrksjBNaV85C14/BRMHhsFTRXg+02jW2II4tP4agppbbmHWRoOvRqPjTiAf5PBy9cYAoelF9SbkBW1obxK+YTK9H1bmFjIq3hyYLX5zaWxuHbI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Cyveillance_Blocks
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
