env:
  global:
    - secure: WbqPs4e7KwN2cR89ivzpo4Q7DkVa8+M2JALLSo5EAEKOnExMQgHjib+Sm9k03utbgK88bGmlMGveZwPxGt7RlhimUXYvkil1Uw04g/+NN8KNZWU/JGhSnKmHNf3Nu2KAQnQEV2Bq8R9y9vsvit3nK4KfcccjdhTciy/joP1V8cz3EFZXf4vmySOB8l73PbhoukFjMz6mMeGNEE4/rJhzbTWGm20N3l+ciOZogZDdgzHwfPEAVC8IHAJpXU/ALSD71lGDw48twioTgd5ICLbge8JQzFiRjoVwyMCwGs5p47TmQ2x9Op57U3K/kqqJzeg6lfTRQMnM/AoOQqqnp36EmH4efNs+j60vC+EE66r1+pWL2ppxNgHQKi96XznpOYDjD+r1oC5daISfMxhrDxvvUdg27E4sGgDN7bON8nj7b2Tqb2yV7xB+oYE/vgVx2NqT+w7DD/xbHTTyaslBO+bA1LcQWSZb9tPGbrVUIKcjK8a8zqkNbjkXX+99x2xJzWF5KV2rcofNbcvB53hZvZP79CWGZPNE8i35n97QjYnXdMjD/e9vGMPG/3A1hUBfAuYIJEENBxgY3OeBBpHQsmVA77TwReZo1VQqlfXhjnIQRsmY6jpl8l88KO1d6igGwfBkjWprf/GAlmWShKcV+S6zXVxAzJ5eKwuI/3I9N8hCpzE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Cyveillance_Blocks
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
