env:
  global:
    - secure: S1yMMDC20l0dP/El836k0M1qGR4nsNTjGpE7i5CZi9dvtoBe+XyaPrprnfS3ZsjlpF20L2Ufhm/Jkerl9Bk4mQNZ61V3s1pVLquS4UTHKCLIkhMcnrOHShgDjyjP3bb/sBic1uX0toqwWKJLBD7QphmyIPW0TwFTPQ3RW08siXlbDOBmbB5ODz30GU190Iz7fA9d3nWj2hEh7T28hCqyXiSXeFLlpfUagfs9u85AxX1UB5JhPOiZ2SV2oneufPyg9GHUpa1InvbIGfhz0k7GpGD2VW2NezFqpUZ9M+01g3ORWmLmYa0LpkuYI2E2Jsk9xPlkyCkG3Vp//oa4o27LPn9zPKEEQKm3A+NhE9lJrSihIsE8+xboCfqd8/6eLQVfUV9yipwVuHyr7rfatAGc6OCeZ8UHSWgMsi4H2bwpdUCtUrol8eQQSbumKsHEq/hagRdHp5nxxUbPI36KYSJZs78rO7beid8mvFZIGy4EA2PBab84b7xq16rfrQntSz70sPFUmHowKIFRTK4BoerjEBNA6PKAmWDKiVHIVKptgw0IrwzX4f3pxdDGCLh+Jhkt37nH1R1JLjUV7qTYTfCgBmVI927uWtnk90gOfBD9HKfmU46FjbkyrF1MEssO99DkS3wU28y9xo2n1owY3sOBpm8dfvwn3vW627p6T9/bON4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Cyveillance_Blocks
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
