env:
  global:
    - secure: eOnfdlZhVuxS8dgDVT3KLY/pPqReZo+jahMgaHwCI43d5zvFeD39QoBZRUbSOtdHLirJg6ruathACex7ARg1ZHSlMI+lBpJyrwpsjltQculYQHeDwrUrLsJmMSKFYJ2jMoZ4q9Bi1lpgR+gEKxjE/ULP5rymErd2RN0/I3ECdO8JnxWq6xg37rgTXa6UH7wLUJKN2yXuBTj77j75W4NmAt3HPq6Dvv34cAccuzHoxKL9TrRlqHYw9qYoL7rIhy8f3STWx+plnvceNUtU/bCQyp589rSswUQTLbRpoHLfSXqCVtZL88U/dvlX2JhaQIUfY2uh6EwRj8zUrwIZ3vbQEFJFVa7JoYSLRGnJrdaBYtxxeZlWrMf6aR4yHkLD8Q9n6cEL/OrluaxTrAWWuIxR5d9B+NofdWOGTW/Yi81VDw6n55P2DbVVTgCLGbesmGqi5wRHjRZbFTOESjrh9q+LDXteeQ5Htr2Rncz+IZr6J6/DqmNliGtn6kMvfjcnFVeAJwh14+6L20Fz9JM1Ryq5gW0uw3Azxuwm+pyFlT3K+BgHr2XklW9RfiygYs5/jwbCUBEnYGaeCYp0SbVlsJXKBnBV8cXBGlkGg1l9h8ulG6BeTbTr7pZRL8nZzqBQ6iAF9G0ezPxKmJT+ZmeMHCX+48++HG1BGd3ae2q/n/HQ+W8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Cyveillance_Blocks
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
