env:
  global:
    - secure: kPobLVM3t7dT3e6KVkMLEVVfMD3m0YlWhK0mniHG+0gWjb3j8MUlTmn4x4BaHFrBeRgji6J/UpaM+2dJuoxo+0g8ZOVtqeDr86+zqhQVYf01aOrSEGoK+1RyKgwKs3Y38n/G5dxDXu//Ni3GhhHaQcTFWg8EPfQyAUWxAsG+ziTGkZbj8ZbWNYwwhP1bMRTG9WJVptd2xGfW5AE3k28GrE+Q5Do38D/vA66Gvlqp+pt5tRLJYRPEmbWpmgA3IJ3UHlWidWWwcbUTm/+WHOGhmpKQdPVKarZCNb3h5nV65JHV8J/cl+400qNEnf7VQFF2exSyOZmrF+Sq/r7H2QlVeW+MLKgo8Ea3wP+vnBxYh/GB1OWk7tNaUbRxl34epHfv+QtmLQlDFFFwG21IxC6qpXaA7BICHw2n/VECarcFUku4gvO+qgIEFDM/S1VY780KsjLncfjTBSZidlh01cd9pvzKtW9ErFgXgc/WfKyCttnoZiPYmLj4IbkcdXIVsNtOGxDF1lV4E9dGkKfN5ouNwAcws5G0a+8hwmrNFhcaKX2mk/Y9nRqzJ4PGmAYPieCK2w3xEUa4n8HrzYU01R40GFsDL2x5IVlqo03WpROPk1cLGGhMx3hfyRnsoibA0ueH4jB0sg89seuqE0emMqZbPejXCfyfghRxtm9utkpOu/g=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Cyveillance_Blocks
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
